language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - ENABLE_SECOND_LEVEL_CACHE=1
  - ENABLE_SECOND_LEVEL_CACHE=0

before_script:
  - psql -c 'DROP DATABASE IF EXISTS doctrine_tests;'
  - psql -c 'DROP DATABASE IF EXISTS doctrine_tests_tmp;'
  - psql -c 'create database doctrine_tests;'
  - psql -c 'create database doctrine_tests_tmp;'
  - mysql -e 'create database IF NOT EXISTS doctrine_tests_tmp;create database IF NOT EXISTS doctrine_tests;'
  - composer install --prefer-dist --dev

script: 
    phpunit -v --configuration tests/travis/sqlite.travis.xml
    phpunit -v --configuration tests/travis/mysql.travis.xml
    phpunit -v --configuration tests/travis/pgsql.travis.xml

after_script:
  - php vendor/bin/coveralls -v
