language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - mysql
  - postgres

before_script:
  - psql -c 'DROP DATABASE IF EXISTS doctrine_tests_tmp;' -U postgres
  - psql -c 'DROP DATABASE IF EXISTS doctrine_tests;' -U postgres
  - psql -c 'CREATE DATABASE doctrine_tests_tmp;' -U postgres
  - psql -c 'CREATE DATABASE doctrine_tests;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS doctrine_tests_tmp;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS doctrine_tests;'
  - composer install --prefer-dist --dev

script: 
    phpunit -v --configuration tests/travis/sqlite.travis.xml;
    phpunit -v --configuration tests/travis/mysql.travis.xml;
    phpunit -v --configuration tests/travis/pgsql.travis.xml;

after_script:
  - php vendor/bin/coveralls -v
